cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ack'
brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'boot-clj'
brew 'coreutils'
brew 'ctags'
brew 'git'
brew 'git-lfs'
brew 'gnu-sed'
brew 'go'
brew 'grc'
brew 'leiningen'
brew 'mycli'
brew 'neovim/neovim/neovim'
brew 'openssl'
brew 'packer'
brew 'parallel'
brew 'python'
brew 'reattach-to-user-namespace'
brew 'readline'
brew 'ruby-build'
brew 'rbenv'
brew 'rlwrap'
brew 'shellcheck'
brew 'ssh-copy-id'
brew 'the_silver_searcher'
brew 'tmux'
brew 'unrar'
brew 'wget'

cask 'dockertoolbox'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'macdown'
cask 'macvim'
cask 'postico'
cask 'seashore'
cask 'slack'
cask 'spotify'
cask 'vlc'
cask 'wireshark'
